"""Initial schema

Revision ID: 0e05fa510389
Revises: 
Create Date: 2026-01-01 18:20:41.864373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '0e05fa510389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_event_created', 'system_events', ['created_at'], unique=False)
    op.create_index('idx_system_event_source', 'system_events', ['source', 'source_type'], unique=False)
    op.create_index('idx_system_event_tenant', 'system_events', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_system_event_type', 'system_events', ['event_type', 'severity'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_severity'), 'system_events', ['severity'], unique=False)
    op.create_index(op.f('ix_system_events_source'), 'system_events', ['source'], unique=False)
    op.create_index(op.f('ix_system_events_tenant_id'), 'system_events', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_parent', 'tenants', ['parent_id'], unique=False)
    op.create_index('idx_tenant_slug', 'tenants', ['slug'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('sso_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('sso_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_sso', 'users', ['sso_provider', 'sso_id'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('token_prefix', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_active', 'api_tokens', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_token_prefix', 'api_tokens', ['token_prefix'], unique=False)
    op.create_index('idx_token_tenant_user', 'api_tokens', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_tenant_id'), 'api_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('http_method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_tenant_action', 'audit_logs', ['tenant_id', 'action'], unique=False)
    op.create_index('idx_audit_tenant_resource', 'audit_logs', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('repository_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('repository_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_tenant', 'projects', ['tenant_id'], unique=False)
    op.create_index('idx_project_tenant_name', 'projects', ['tenant_id', 'name'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('user_tenant_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_user_tenant', 'user_tenant_roles', ['user_id', 'tenant_id'], unique=True, postgresql_where='revoked_at IS NULL')
    op.create_index('idx_user_tenant', 'user_tenant_roles', ['user_id', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_user_tenant_roles_tenant_id'), 'user_tenant_roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_tenant_roles_user_id'), 'user_tenant_roles', ['user_id'], unique=False)
    op.create_table('worker_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('worker_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('default_tags', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('default_capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('arch', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('max_concurrent_runs', sa.Integer(), nullable=False),
    sa.Column('provisioning_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_active', 'worker_templates', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_template_tenant_type', 'worker_templates', ['tenant_id', 'worker_type'], unique=False)
    op.create_index(op.f('ix_worker_templates_name'), 'worker_templates', ['name'], unique=False)
    op.create_index(op.f('ix_worker_templates_tenant_id'), 'worker_templates', ['tenant_id'], unique=False)
    op.create_table('test_suites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['test_suites.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suite_parent', 'test_suites', ['parent_id'], unique=False)
    op.create_index('idx_suite_path', 'test_suites', ['tenant_id', 'path'], unique=False)
    op.create_index('idx_suite_tenant_project', 'test_suites', ['tenant_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_test_suites_project_id'), 'test_suites', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_suites_tenant_id'), 'test_suites', ['tenant_id'], unique=False)
    op.create_table('test_workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('worker_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('arch', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('worker_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('max_concurrent_runs', sa.Integer(), nullable=False),
    sa.Column('current_active_runs', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('health_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['worker_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worker_available', 'test_workers', ['tenant_id', 'is_available', 'status'], unique=False)
    op.create_index('idx_worker_heartbeat', 'test_workers', ['last_heartbeat_at'], unique=False)
    op.create_index('idx_worker_tenant_status', 'test_workers', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_worker_tenant_type', 'test_workers', ['tenant_id', 'worker_type'], unique=False)
    op.create_index(op.f('ix_test_workers_last_heartbeat_at'), 'test_workers', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_test_workers_name'), 'test_workers', ['name'], unique=False)
    op.create_index(op.f('ix_test_workers_status'), 'test_workers', ['status'], unique=False)
    op.create_index(op.f('ix_test_workers_tenant_id'), 'test_workers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_workers_worker_type'), 'test_workers', ['worker_type'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('test_tags', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('worker_assignment', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_active', 'schedules', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_schedule_tenant_project', 'schedules', ['tenant_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_schedules_project_id'), 'schedules', ['project_id'], unique=False)
    op.create_index(op.f('ix_schedules_tenant_id'), 'schedules', ['tenant_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('test_id', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('is_flaky', sa.Boolean(), nullable=False),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=True),
    sa.Column('pass_rate_percent', sa.Float(), nullable=True),
    sa.Column('last_run_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_case_active', 'test_cases', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_test_case_suite', 'test_cases', ['suite_id'], unique=False)
    op.create_index('idx_test_case_tenant_test_id', 'test_cases', ['tenant_id', 'test_id'], unique=False)
    op.create_index(op.f('ix_test_cases_name'), 'test_cases', ['name'], unique=False)
    op.create_index(op.f('ix_test_cases_suite_id'), 'test_cases', ['suite_id'], unique=False)
    op.create_index(op.f('ix_test_cases_tenant_id'), 'test_cases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_cases_test_id'), 'test_cases', ['test_id'], unique=False)
    op.create_table('test_failure_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('failure_pattern_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('failure_message', sa.TEXT(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('is_flaky', sa.Boolean(), nullable=False),
    sa.Column('is_regression', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('affected_run_ids', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_failure_flaky', 'test_failure_analysis', ['tenant_id', 'is_flaky'], unique=False)
    op.create_index('idx_failure_pattern', 'test_failure_analysis', ['failure_pattern_hash'], unique=False)
    op.create_index('idx_failure_resolved', 'test_failure_analysis', ['tenant_id', 'is_resolved'], unique=False)
    op.create_index('idx_failure_tenant_test', 'test_failure_analysis', ['tenant_id', 'test_case_id'], unique=False)
    op.create_index(op.f('ix_test_failure_analysis_tenant_id'), 'test_failure_analysis', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_failure_analysis_test_case_id'), 'test_failure_analysis', ['test_case_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('suite_id', sa.Uuid(), nullable=True),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('webhook_source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('jenkins_job_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('jenkins_build_number', sa.Integer(), nullable=True),
    sa.Column('jenkins_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('repository_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('commit_hash', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('commit_message', sa.TEXT(), nullable=True),
    sa.Column('release_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('release_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('test_framework', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('test_framework_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('test_tags', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('test_filter', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('skipped_tests', sa.Integer(), nullable=False),
    sa.Column('error_tests', sa.Integer(), nullable=False),
    sa.Column('coverage_percent', sa.Float(), nullable=True),
    sa.Column('coverage_report_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('log_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('report_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['test_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_run_release', 'test_runs', ['tenant_id', 'release_id'], unique=False)
    op.create_index('idx_test_run_tenant_created', 'test_runs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_test_run_tenant_status', 'test_runs', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_test_run_worker_status', 'test_runs', ['worker_id', 'status'], unique=False)
    op.create_index(op.f('ix_test_runs_commit_hash'), 'test_runs', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_test_runs_project_id'), 'test_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_runs_release_id'), 'test_runs', ['release_id'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_runs_suite_id'), 'test_runs', ['suite_id'], unique=False)
    op.create_index(op.f('ix_test_runs_tenant_id'), 'test_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_runs_worker_id'), 'test_runs', ['worker_id'], unique=False)
    op.create_table('test_coverage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('total_statements', sa.Integer(), nullable=False),
    sa.Column('covered_statements', sa.Integer(), nullable=False),
    sa.Column('coverage_percentage', sa.Float(), nullable=False),
    sa.Column('file_coverage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('total_branches', sa.Integer(), nullable=True),
    sa.Column('covered_branches', sa.Integer(), nullable=True),
    sa.Column('branch_coverage_percentage', sa.Float(), nullable=True),
    sa.Column('report_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('report_format', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coverage_percentage', 'test_coverage', ['coverage_percentage'], unique=False)
    op.create_index('idx_coverage_tenant_project', 'test_coverage', ['tenant_id', 'project_id'], unique=False)
    op.create_index('idx_coverage_tenant_run', 'test_coverage', ['tenant_id', 'test_run_id'], unique=False)
    op.create_index(op.f('ix_test_coverage_project_id'), 'test_coverage', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_coverage_tenant_id'), 'test_coverage', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_coverage_test_run_id'), 'test_coverage', ['test_run_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('test_run_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=True),
    sa.Column('test_id', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('test_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('stack_trace', sa.TEXT(), nullable=True),
    sa.Column('stdout', sa.TEXT(), nullable=True),
    sa.Column('stderr', sa.TEXT(), nullable=True),
    sa.Column('screenshots', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('log_files', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_result_run_status', 'test_results', ['test_run_id', 'status'], unique=False)
    op.create_index('idx_test_result_tenant_case', 'test_results', ['tenant_id', 'test_case_id'], unique=False)
    op.create_index('idx_test_result_tenant_run', 'test_results', ['tenant_id', 'test_run_id'], unique=False)
    op.create_index(op.f('ix_test_results_status'), 'test_results', ['status'], unique=False)
    op.create_index(op.f('ix_test_results_tenant_id'), 'test_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_case_id'), 'test_results', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_id'), 'test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_case_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_tenant_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_status'), table_name='test_results')
    op.drop_index('idx_test_result_tenant_run', table_name='test_results')
    op.drop_index('idx_test_result_tenant_case', table_name='test_results')
    op.drop_index('idx_test_result_run_status', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_coverage_test_run_id'), table_name='test_coverage')
    op.drop_index(op.f('ix_test_coverage_tenant_id'), table_name='test_coverage')
    op.drop_index(op.f('ix_test_coverage_project_id'), table_name='test_coverage')
    op.drop_index('idx_coverage_tenant_run', table_name='test_coverage')
    op.drop_index('idx_coverage_tenant_project', table_name='test_coverage')
    op.drop_index('idx_coverage_percentage', table_name='test_coverage')
    op.drop_table('test_coverage')
    op.drop_index(op.f('ix_test_runs_worker_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_tenant_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_suite_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_release_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_project_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_commit_hash'), table_name='test_runs')
    op.drop_index('idx_test_run_worker_status', table_name='test_runs')
    op.drop_index('idx_test_run_tenant_status', table_name='test_runs')
    op.drop_index('idx_test_run_tenant_created', table_name='test_runs')
    op.drop_index('idx_test_run_release', table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_test_failure_analysis_test_case_id'), table_name='test_failure_analysis')
    op.drop_index(op.f('ix_test_failure_analysis_tenant_id'), table_name='test_failure_analysis')
    op.drop_index('idx_failure_tenant_test', table_name='test_failure_analysis')
    op.drop_index('idx_failure_resolved', table_name='test_failure_analysis')
    op.drop_index('idx_failure_pattern', table_name='test_failure_analysis')
    op.drop_index('idx_failure_flaky', table_name='test_failure_analysis')
    op.drop_table('test_failure_analysis')
    op.drop_index(op.f('ix_test_cases_test_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_tenant_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_suite_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_name'), table_name='test_cases')
    op.drop_index('idx_test_case_tenant_test_id', table_name='test_cases')
    op.drop_index('idx_test_case_suite', table_name='test_cases')
    op.drop_index('idx_test_case_active', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_schedules_tenant_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_project_id'), table_name='schedules')
    op.drop_index('idx_schedule_tenant_project', table_name='schedules')
    op.drop_index('idx_schedule_active', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_test_workers_worker_type'), table_name='test_workers')
    op.drop_index(op.f('ix_test_workers_tenant_id'), table_name='test_workers')
    op.drop_index(op.f('ix_test_workers_status'), table_name='test_workers')
    op.drop_index(op.f('ix_test_workers_name'), table_name='test_workers')
    op.drop_index(op.f('ix_test_workers_last_heartbeat_at'), table_name='test_workers')
    op.drop_index('idx_worker_tenant_type', table_name='test_workers')
    op.drop_index('idx_worker_tenant_status', table_name='test_workers')
    op.drop_index('idx_worker_heartbeat', table_name='test_workers')
    op.drop_index('idx_worker_available', table_name='test_workers')
    op.drop_table('test_workers')
    op.drop_index(op.f('ix_test_suites_tenant_id'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_project_id'), table_name='test_suites')
    op.drop_index('idx_suite_tenant_project', table_name='test_suites')
    op.drop_index('idx_suite_path', table_name='test_suites')
    op.drop_index('idx_suite_parent', table_name='test_suites')
    op.drop_table('test_suites')
    op.drop_index(op.f('ix_worker_templates_tenant_id'), table_name='worker_templates')
    op.drop_index(op.f('ix_worker_templates_name'), table_name='worker_templates')
    op.drop_index('idx_template_tenant_type', table_name='worker_templates')
    op.drop_index('idx_template_active', table_name='worker_templates')
    op.drop_table('worker_templates')
    op.drop_index(op.f('ix_user_tenant_roles_user_id'), table_name='user_tenant_roles')
    op.drop_index(op.f('ix_user_tenant_roles_tenant_id'), table_name='user_tenant_roles')
    op.drop_index('idx_user_tenant', table_name='user_tenant_roles')
    op.drop_index('idx_unique_user_tenant', table_name='user_tenant_roles', postgresql_where='revoked_at IS NULL')
    op.drop_table('user_tenant_roles')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index('idx_project_tenant_name', table_name='projects')
    op.drop_index('idx_project_tenant', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_resource', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_action', table_name='audit_logs')
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_tenant_id'), table_name='api_tokens')
    op.drop_index('idx_token_tenant_user', table_name='api_tokens')
    op.drop_index('idx_token_prefix', table_name='api_tokens')
    op.drop_index('idx_token_active', table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_sso', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index('idx_tenant_slug', table_name='tenants')
    op.drop_index('idx_tenant_parent', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_system_events_tenant_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_source'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_severity'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index('idx_system_event_type', table_name='system_events')
    op.drop_index('idx_system_event_tenant', table_name='system_events')
    op.drop_index('idx_system_event_source', table_name='system_events')
    op.drop_index('idx_system_event_created', table_name='system_events')
    op.drop_table('system_events')
    # ### end Alembic commands ###

