"""Add current_tenant_id to users

Revision ID: f035cde61025
Revises: 0e05fa510389
Create Date: 2026-01-01 21:43:39.803209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f035cde61025'
down_revision = '0e05fa510389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_tenant_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'tenants', ['current_tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_tenant_id')
    # ### end Alembic commands ###

